### ISSUE TITLE
Feature Idea: Bring back the med station

### ISSUE THREAD

**Issue by caligari87** [caligari87/Ugly-as-Sin#100]
Revamped version of old medical station.

**Requires:**
- up to 3 wrapped medikits (injector, stim, bloodbag)
- 1 battery for power

**Function:** Use inventory object to load medikits. Drop in place (automatically takes best available battery), stand nearby, and [Use] the station. Basically "tops off" any of the player's medical needs with the increased speed that would normally come from having a second player treat. Tops off blood at an increased rate, applies estimated optimal amounts of 2F to burns, and gives the player a stim when complete, if available. If player already has stims, gives a partial to top off and avoid OD. Double-tap use to pick back up.

**Drawbacks:** Player still needs to strip armor. soft-locks player in place; if player moves away while treating, sequence aborts early. Can only accept wrapped medikits, which are NOT returned when picked back up.

**Comment by MatthewTheGlutton** [comment]
suggestion: have it hard-lock the player in place, to emulate the machinery wrapping around the person (which I was never able to do in the old Decorate implementation of this).

Tempted also to suggest yonic imagery where the current 2F injector is phallic, but maybe that's a bit much

**Comment by caligari87** [comment]
Closing, this isn't really interesting to me any more with all the available medical options we have now between HD and UaS. More effort than it's worth for plain nostalgia.
