### ISSUE TITLE
Focus Zoom: Pistol resets zoom-in when firing

### ISSUE THREAD

**Issue by caligari87** [caligari87/Ugly-as-Sin#127]
[Reported in Discord](https://discord.com/channels/425899670800433153/425903466305683458/773532135062503454) by **Lotus#1566**

When standing still and zoomed in with focus zoom, shooting the pistol resets the zoom. Have reproduced the issue, not sure what might be causing it. Possibly some weird quirk on HD's side.

**Comment by nicothegoat** [comment]
This only affects the focus key mode, as it checks `isFocussing` which is (indirectly) set to false in the pistol's `shoot` state.
One way to work around this would be to make it check for zoom and use directly.

**Comment by caligari87** [comment]
Possibly. I'm more interested in why HD has that `A_GiveInventory("IsMoving",1);` for the pistol and not the revolver. Will ask Matt.

**Comment by caligari87** [comment]
Closed, this is fixed in [2172c40858](https://codeberg.org/mc776/HideousDestructor/commit/2172c408581f4c251c4a7687f1f95b63621e42b9) on HD's side.
