### ISSUE TITLE
states can only be defined for actors - won't launch

### ISSUE THREAD

**Issue by nesbros** [caligari87/Ugly-as-Sin#136]
...Ugly-as-Sin_v4.5.0a.pk3:modules/items/ammoboxes.zsc, line 68: UaS_9mmBox: States can only be defined for actors.
Ugly-as-Sin_v4.5.0a.pk3:modules/items/ammoboxes.zsc, line 97: UaS_ShellBox: States can only be defined for actors.
Ugly-as-Sin_v4.5.0a.pk3:modules/items/ammoboxes.zsc, line 124: UaS_7mmBox: States can only be defined for actors.
Ugly-as-Sin_v4.5.0a.pk3:modules/items/ammoboxes.zsc, line 151: UaS_355Box: States can only be defined for actors.
Ugly-as-Sin_v4.5.0a.pk3:modules/items/ammoboxes.zsc, line 176: UaS_RocketBox: States can only be defined for actors.

Execution could not continue.

174 errors, 0 warnings while compiling Ugly-as-Sin_v4.5.0a.pk3:zscript.zsc

states can only be defined for actors, so it won't launch. I am using the latest version of gzdoom, HDest, and,
of course, UaS.

**Comment by caligari87** [comment]
resolved in discord
