### ISSUE TITLE
Rations: All rations removed from backpack on level change

### ISSUE THREAD

**Issue by caligari87** [caligari87/Ugly-as-Sin#142]
Reported by Kegan on Discord:
﻿
> Oh crap I forgot ping @Caligari87 about this, but there's a weird quirk with rations where if you have them in your backpack, you take them all out when you go to the next level. Also curry and rice description has a small typo where potatoes is spelled "potatos"

> Yeah normal rations we've found out in the field, I've put them in my backpack, and then when we cross over into the next level, they're all out in my normal inventory again, it's a weird bug

Might have something to do with consolidation

**Comment by nicothegoat** [comment]
bFitsInBackpack is being checked before the ration can tick - setting the flag in BeginPlay or PostBeginPlay instead should work

**Comment by caligari87** [comment]
aaaaah, okay. Thank you!
