### ISSUE TITLE
Ammo Pouches: sprites for empty pouches.

### ISSUE THREAD

**Issue by Accensus** [caligari87/Ugly-as-Sin#147]
Hello, I am Ace, and I'm an airhead. I keep dropping pouches and forget if I emptied them or not.

#141 would probably help in my case in singleplayer since I don't ever drop pouches during combat, but in multiplayer an empty pouch sprite would be appreciated, mainly because if you pick up an unwanted pouch you have to go through the process of removing *all* of them until you're left with the desired ones. ~~Until you forget again.~~

Taking the lazy route with the horizontal pouch as is the case with the backpack would suffice too.

**Comment by caligari87** [comment]
I'll probably add the sideways sprite like the backpack yeah.

Pondering on this, I could also add a keybind/combo (hold `Use` while dropping?) to simply drop a spare pouch without attempting to split any spare ammo into it. Would probably just ignore bulk calculations so you might end up with overstuffed pouches if you drop too many empties, but that already happens with merging too so I'm not exceptionally concerned about adding a fail state.

**Comment by Accensus** [comment]
That's also not a bad idea at all. I like it.
