### ISSUE TITLE
Tossing an ammo pouch that has ammo in it sometimes (rarely) causes a VM abort.

### ISSUE THREAD

**Issue by caligari87** [caligari87/Ugly-as-Sin#148]
![image](https://user-images.githubusercontent.com/6425795/112737106-8c8ff400-8f1d-11eb-849b-990d70fc9116.png)

Reported by D2Icarus#9304 on Discord

**Comment by caligari87** [comment]
Another example error screenshot
![image](https://user-images.githubusercontent.com/6425795/112737379-c661fa00-8f1f-11eb-847b-cf76db3fec68.png)

**Comment by Accensus** [comment]
It's a division by zero error.
https://github.com/caligari87/Ugly-as-Sin/blob/657f2b59bf703342516fadc1530e08b0731cb832/ammopouch/module/ammopouch_bulk.zsc#L45
UnitBulk will be 0 if playing on 0 encumbrance.

**Comment by caligari87** [comment]
Got it, will address later.
