### ISSUE TITLE
Crash when enabling the AI module's Searching feature

### ISSUE THREAD

**Issue by TheoDrHashiriya** [caligari87/Ugly-as-Sin#161]
- I did make sure to launch HD without UaS. Does not crash.

Reproduction:
1. Load latest HD repo with latest UaS repo. (Load order: HD, UaS)
2. Enable the AI module along with its Searching feature.
3. Launch new game.
4. Fire loud weapon / Alert enemies

**Comment by caligari87** [comment]
This is a known issue, I'm working on fixing it but it may take a while. In the meantime, please disable the Searching feature of the AI module.

I've re-opened the issue so it's visible until I finish the fix, for anyone seeking to report the same.

**Comment by caligari87** [comment]
Closing as I believe this was fixed a while ago. If nothing else, Searching is an unsupported / disabled feature right now, and HDest's new enemy AI serves much the same purpose.
