### ISSUE TITLE
Stealth module breaks the Night Vision goggles

### ISSUE THREAD

**Issue by qee1540** [caligari87/Ugly-as-Sin#163]
When the blue shade under the hud appears it will remove the night vision effect rendering it useless to use in the dark

**Comment by caligari87** [comment]
Known issue with how HD uses the +SHADOW flag now. I need to revamp the feature.

**Comment by MarinaGryphon** [comment]
May be fixed by https://codeberg.org/mc776/hideousdestructor/pulls/139.
