### ISSUE TITLE
Deathfade applies to all players if one player has it set on?

### ISSUE THREAD

**Issue by caligari87** [caligari87/Ugly-as-Sin#164]

**Comment by nicothegoat** [comment]
It seems to work fine on my end. Are you 100% sure this is UaS death fade running for all players and not HD's built in death fade?
(For reference, HD's death fade quickly fades back to normal, whereas UaS death fade lasts until resurrected/respawned.)

**Comment by caligari87** [comment]
Believe this was fixed at some point.
