### ISSUE TITLE
gravity rework broke sling

### ISSUE THREAD

**Issue by caligari87** [caligari87/Ugly-as-Sin#170]
From the Discord:
> I don’t know if you already know this but the recent gravity overhaul slightly broke the stabilizer, even one small downward step unbraces it

Will need to look into this, probably as part of a general rework on the sling/stabilizer.

**Comment by VBawss** [comment]
This has been working for me as a quick fix for some time.
![slingfix](https://user-images.githubusercontent.com/27232556/145441153-5d114e72-471f-49aa-a372-5fa45fa50cbb.png)

**Comment by mc776** [comment]
This might be related to how falling even fairly short heights will cause some minor stun.

I'll look into toning that down a bit and ignoring slower impacts.

**Comment by mc776** [comment]
I've just tried messing around with the movement. The current is actually what I want.

I think it's best to increase the maximum stun threshold. 10 might be a *little* high but it might not.

**Comment by caligari87** [comment]
Okay, for now I'll increase the stun threshold to 10 just to get it working. This is pending a pretty big overhaul anyway.

For reference, I'll be rebranding the sling as a gyroscopic stabilizer system. A system will come with one core and two attachments. An attachment part is placed on the weapon (taking up a `weaponstatus` slot with a UID of some kind) and needs to be manually removed if you want to swap it to another gun. The core stays on the player and can be activated or deactivated. When active, it will attempt to keep the gun braced at all times, maybe with some sensitivity reduction to the player's mouse. Sprinting will temporarily deactivate, but it'll reactivate as soon as you slow down. Spawns will be rare. They'll have an internal battery like the NVG, which is taken up based on how often the system needs to "rebrace" the gun.
