### ISSUE TITLE
[Bug] AmmoPouch deletes slugs whenever it gets updated

### ISSUE THREAD

**Issue by Cryomundus** [caligari87/Ugly-as-Sin#171]
To see it in action, you'll need peppergrinder's slugs and at least 1 other ammotype. Add the slugs to the pouch, then add/remove the other ammo and drop the ammopouch. When you pick it up again, the slugs are gone. A similar thing happens on level transition, presumably due to attempted ammo consolodation.

**Comment by caligari87** [comment]
In theory the ammopouch should be mod-agnostic, so I'm not sure where the problem would be. Does the slug ammo from peppergrinder do something special that other ammo doesn't?

**Comment by FDAapproved** [comment]
Discussed this some with other people on the HD-Discord, we concluded it may to be due to bulletlib's ammo enabling/disabling features, which shouldn't be caused by UAS. If you check that and it's still happening, this'd probably be worth looking into further
