### ISSUE TITLE
New alternative trauma kit UI cuts off wound description

### ISSUE THREAD

**Issue by FistsAkimbo** [caligari87/Ugly-as-Sin#177]
![cutoff](https://user-images.githubusercontent.com/44789472/147796598-72bf0b17-e634-426a-be20-a67bf63f4c93.png)

^the above is at 1360x768 with a fullscreen HUD scale setting of 3.

The new UI looks great, but also suffers from cutoff on lower resolutions with higher levels of HUD scaling. I noticed that this trauma kit UI's scaling was handled with its own unique CVAR, does current implementation conflict with this resulting in its removal? Dropping fullscreen HUD scaling down a level makes everything quite small, along with causing a mismatch in display sizes for other messages. Only other idea would be to break up the wound type and wound location to be on two separate lines, then have two arrows point to the selected wound instead of one, if the old HUD style is officially discontinued.

**Comment by caligari87** [comment]
I think the solution for this is to bring back the UI scaler. At `0.75`, it seems to fit just fine. 
![image](https://user-images.githubusercontent.com/6425795/147797681-d17dd883-1280-4ae9-a392-5f2cfc7701a2.png)
