### ISSUE TITLE
excessive 7mm when using overspawn on any HD version past 4.7.0a

### ISSUE THREAD

**Issue by hochiminhts** [caligari87/Ugly-as-Sin#179]
Using Bogus' HD range as an example, with HD v4.7.0a, with the following settings:

![image](https://user-images.githubusercontent.com/76270954/149431386-0e0a2404-e303-4e56-89db-6fbc0fa3d712.png)

It's like this:

![image](https://user-images.githubusercontent.com/76270954/149431515-51fdc6db-14d4-47f8-a395-77cd66fc54f3.png)

While on ANY version past v4.7.0a, it can get as excessive as this:

![image](https://user-images.githubusercontent.com/76270954/149431660-d18f3757-ff9a-4725-b5d6-eb7ef2887f27.png)

(same settings as shown above)

There's only 12 7.76 mags there normally, but there's practically triple the ammo that would've been in the mags on the ground when using overspawn at this rate.

No other ammo type seems to be affected like this either.

I've attempted to try and pinpoint whether an update may have done this or not, but I've gone as far back as the commit where it was changed to 4.7.1 and got no results.

EDIT: A video clip of one of the people I play with finding this happen in a mapset.
[https://streamable.com/aec709](url)

**Comment by caligari87** [comment]
This is almost certainly an issue introduced by the 7mil recasts. The scarcity system isn't aware of that yet, so it thinks the mags have a bajillion rounds in them.

I'll try to address it sometime this weekend.

**Comment by caligari87** [comment]
Fixed with special case for both 7mm clips and mags, at least the stock ones. I don't know if there's any way to address this generically. Closed for now unless something else crops up.
