### ISSUE TITLE
Looting: Allow multiple fallback items again

### ISSUE THREAD

**Issue by caligari87** [caligari87/Ugly-as-Sin#207]
So I think to best support the request for multiple loot items from fallback, I'm going to have a little fun with math. Currently the formula is
```cs
if (frandom[loot](0,1) < UaS_LootingFactor) {
  // snip, give an item
  fullysearched = true;
}
```
What I'm going to do is change it like so:
```cs
if (frandom[loot](0,1+founditems) < UaS_LootingFactor) {
  // snip
  founditems++;
}
else { fullysearched = true; }
```
This would make it so every found item divides-down your effective lootfactor. So for example if your lootfactor is 0.5, you have a 50% chance to find one item, if successful then 25% chance to find another item, then 16.6%, then 12.5%, 10%, 8.3%, etc. If you don't roll an item, then that's it, you're done. Theoretically you could roll infinite items but in practice it'll never happen. A lootfactor of 1.0 guarantees at least one item found every time.

**Comment by wallabra** [comment]
Isn't this kind of an inverse exponential distribution type situation (x ^ -n)? You can use that to get a random value between 0 and infinity (of course in practice you'll have a hard max cap, probably a min between a CVar and a cap in the loot table), a distzribution affected both by `UAS_LootFactor` and the weight defined in the loot table if any.

I'll do a PR later to demonstrate if I may.

**Comment by caligari87** [comment]
I appreciate the enthusiasm but I don't think that's necessary. I've got a nearly complete implementation about ready to go

**Comment by wallabra** [comment]
Nonetheless I definitely should get acquainted with the codebase. Perhaps this is good practice for that, and who knows if the random distribution of loot will be more interesting.

**Comment by wallabra** [comment]
@caligari87 I just finished my commit, the timing is pretty funny.

I take a different, more numeric approach. Instead of a chance of dropping multiple loot (fallback loot, although monsters don't spawn with owned `HDPickup` yet), an exponential function is used to make larger amounts of loot rarer than smaller amounts. See: https://github.com/wallabra/Ugly-as-Sin/commit/21f5598acfe1f446b887c693697b926cfaaa395f

If you want to play around with how this distribution should behave, I have a very simple prototype in Python which simulates it:

```py
"Simulates the loot distribution in wallabra:Ugly-As-Sin commit 21f5598."
import math
import random


class LootDist:
    "Holds the parameters of a loot distribution."

    def __init__(self, base: float = 2.2, factor: float = 3.0, max_x: float = 30.0):
        self.base = base
        self.factor = factor
        self.max_x = max_x

    def transform(self, value):
        "Transforms an uniform distribution value."
        return max(1, self.base ** (value / self.max_x * self.factor) - 1)

    def random_num_loot(self):
        "Transforms a random uniform value using `random.uniform` and floors it down."
        return math.floor(self.transform(random.uniform(1.0, self.max_x)))


if __name__ == "__main__":
    loot_dist = LootDist()
    for n in range(2, 60):
        print(f"{n / 2:.1f} -> {loot_dist.transform(n / 2):.0f}")

```

**Comment by caligari87** [comment]
Yeah this is way more complex than necessary for this feature. I prefer the simplicity of a single controlling variable with easily-comprehensible behavior.

Again, appreciate the effort.
