### ISSUE TITLE
Flashbang grenade

### ISSUE THREAD

**Issue by caligari87** [caligari87/Ugly-as-Sin#22]
Confuse / daze monsters with a bright flash and loud bang.

Implementation:
* Base off existing HD grenade.
* Include handler module that cycles to the flashbang if the grenade key is pressed while the standard grenade is the current weapon.
* Flash will be a bright additive light and a large white sprite, plus a little smoke.
* Use `A_RadiusGive` to drop a flash handler in nearby monster inventory. The handler performs the following effects for some random amount of tics:
  * Keep the monster's target field cleared.
  * Periodically force pain.
  * Modulate the actor's angle/pitch smoothly but randomly. 
  * Consider doing this with a blockthingiterator and actor list instead of inventory items?
* Same handler may also work on players, covering the screen with a white fade and playing a ringing sound

**Comment by caligari87** [comment]
The holdup here is that I really don't care to re-implement the HD grenade, and while it's possible to override the real grenade-thrower somehow, it'll be very clunky.

**Comment by XLightningStormL** [comment]
Any update on this feature?

**Comment by caligari87** [comment]
Not yet. I've taken a soft hiatus from modding (not permanent). Will try to prioritize this when I get back in the zone, as everything *should* be in place to implement it.

**Comment by caligari87** [comment]
Had some voice discussion in Discord, it was suggested that this idea would work better as some kind of gas grenades, via several floating gas actors that give pain counters to monsters touching them

Makes sense as the gas would only need to trigger pain states to affect monster effectiveness, doesn't need complicated sight checks, and would last longer in a given area.

Plus it would interact well with the environment suit, and I could add that togglable gasmask+filters mechanic I always keep wanting to do ever since I played Metro.

**Comment by caligari87** [comment]
Not really interested in doing this anymore. Also doesn't make much sense in a combat situation compared to frags.
