### ISSUE TITLE
Newest Version Of Ugly-As-Sin Shows Scripts In Console And Chat 

### ISSUE THREAD

**Issue by Azalotz** [caligari87/Ugly-as-Sin#223]
![Screenshot_20231027-013638](https://github.com/caligari87/Ugly-as-Sin/assets/103554296/bfdda87c-fe5e-42cf-88a8-265828cf48b2)
![Screenshot_20231027-014015](https://github.com/caligari87/Ugly-as-Sin/assets/103554296/c7eefa3a-3c4f-4e69-be12-09b1eb4668cb)

-
So I Am Still Quite New To The Doom 2 Modding Scene, So I'm Not Really Sure How Scripts, Decorate, And All That Other Stuff Works. 
But My UAS Has Been Showing How The Advanced AI Module Processes The Advanced AI, And Some Other Stuff. 
**I Have Litterally No Idea How To Turn This Off.**
I've Tried To Disable Messages, Turn Off Critical Messages (because that's what it seems to be categorized as) To No Avail.
Mind Helping A Noobie Out?
🤣

**Comment by caligari87** [comment]
You turned on debugging in the Core module. That menu is for debugging only, not to enable or disable modules.

**Comment by Azalotz** [comment]
Oh!!!! IM SO DUMB!
The Older Versions Had You Enable The Core's Via A Menu Similar To That.
Thanks Man! This Is A Great Mod/Revamp Of The Game, Keep Up Tje Great Work!

**Comment by Azalotz** [comment]
TY!
