### ISSUE TITLE
Trauma Kit Not Spawning & Loadout Code Bugged

### ISSUE THREAD

**Issue by Azalotz** [caligari87/Ugly-as-Sin#224]
![Screenshot_20231102-061400](https://github.com/caligari87/Ugly-as-Sin/assets/103554296/3e7ebd17-9673-4cc0-8b09-b29d85129163)
Hey Cali, Sorry To Bother You Again For Something That Is Probably Very Fixable
(I still feel bad about the other day lol)
But I Haven't Seen A Single Trauma Kit Appear, And The Loadout Code Seems To Be Bugged.
I Checked My Medical Module, And It Seemed To Be On.
Did You Perhaps Change The Loadout Code And The Way It Spawns?
![Screenshot_20231102-054852](https://github.com/caligari87/Ugly-as-Sin/assets/103554296/194e2dbc-e2d0-4e12-9400-4728d56963cf)
![Screenshot_20231102-055427](https://github.com/caligari87/Ugly-as-Sin/assets/103554296/aca5a0ba-0e77-410d-8afa-22baba172398)
I've Been Given A New U.A.S Master By Dastrukar, And Seeming To Have Some Issues With DECORATE.
Running Only HD And That Master.

Again, I Do Apologize If This Issue Is Easily Fixable.
Thanks Cali!

**Comment by dastrukar** [comment]
Can't reproduce. You sure you're using the [latest master](https://github.com/caligari87/Ugly-as-Sin/archive/refs/heads/master.zip)?

**Comment by Azalotz** [comment]
> Can't reproduce. You sure you're using the [latest master](https://github.com/caligari87/Ugly-as-Sin/archive/refs/heads/master.zip)?

I'm Using The Latest Version Of HD And Ugly As Sin. (4.10.0b)
But I'll Give The Version You Suggested Me To Try A Try.

**Comment by dastrukar** [comment]
Oh, the trauma kit isn't in the latest release (v4.10.0b). It only recently got added back in, so the getting the latest master should do it. (should also work with v4.10.0b the last time i tested it)

**Comment by Azalotz** [comment]
It Could Be That GZDoom Hasn't Updated Yet. (I'm a delta touch player) I'm On GZDoom DEV (v4.11Pre)

But I'll Mess Around, I'll Let You Know If Its Still Acting Up, Thanks!

**Comment by dastrukar** [comment]
Oh, I found the errors, HD got updated with LANGUAGE strings, and the recent PR also updated some stuff to use it.
You might have to update your HD.

**Comment by Azalotz** [comment]
> Oh, I found the errors, HD got updated with LANGUAGE strings, and the recent PR also updated some stuff to use it. You might have to update your HD.

Ah, Alright. I'll See If HD Has A New Update, And I'll Update You On It. Thanks For The Help Man!

**Comment by Azalotz** [comment]
Everything Seems Up To Date...
GZDoom Is On 4.11
HD Is 4.10.0b.
Hmm. This Could Again Be My Stupidity.
I Have Every HD Version Past 4.5.0a, Gave Those All A Try To No Avail.
It Might Be Delta Touch Having A Heart Attack Lol, I'll See The Play Store For An Update There.

Sorry I'm Being A Burden Lol.

**Comment by Azalotz** [comment]
Yep, Indeed Delta Touch Needed An Update. Updating It Now.

**Comment by dastrukar** [comment]
Try getting the [latest main](https://codeberg.org/mc776/HideousDestructor/archive/main.zip) of HD, not the latest release.
In case you didn't know, you can do it like so:
![image](https://github.com/caligari87/Ugly-as-Sin/assets/32709291/427eb03d-cc1d-4254-8c59-504c1a7c5a4c)

**Comment by Azalotz** [comment]
> Try getting the [latest main](https://codeberg.org/mc776/HideousDestructor/archive/main.zip) of HD, not the latest release. In case you didn't know, you can do it like so: ![image](https://user-images.githubusercontent.com/32709291/279949112-427eb03d-cc1d-4254-8c59-504c1a7c5a4c.png)

Ah, I Never Knew That. I'll Give It A Download.

**Comment by Azalotz** [comment]
Ah, It Worked! 
Thanks Dastrukar. Appreciate It!

**Comment by Azalotz** [comment]
Just Getting Used To Things Around Github, Quite New To The HD Community, Thank You For The Help.
