### ISSUE TITLE
Game freezes while bandaging wounds

### ISSUE THREAD

**Issue by physixcat** [caligari87/Ugly-as-Sin#227]
Was bandaging wounds (had ~10 active I think) and the game froze with
```
_sqrt domain error

_sqrt domain error

_sqrt domain error
```
in the terminal. Don't have other info at the moment, not sure if it had to do with the recent UaS medical commits

**Comment by dastrukar** [comment]
Weird. The error is caused by passing an invalid value to `sqrt()`, but there isn't a single `sqrt()` used anywhere in the code...

**Comment by physixcat** [comment]
Yeah I saw :/ I'll try playing with only UaS loaded and see if it happens again. Could've always been something else

**Comment by physixcat** [comment]
I haven't ran into this again, so I'll just call it a fluke.
