### ISSUE TITLE
Trauma Kit Saline, alt.fire uses wrong text in help menu?

### ISSUE THREAD

**Issue by CannibalHunter** [caligari87/Ugly-as-Sin#236]
using most recent build of hdest and uas

in the help menu of the trauma kit when having the saline selected it says "Alt.Fire saline (break down stimpack)" while it does not use a stimpack but rather a blood bag.

![image](https://github.com/caligari87/Ugly-as-Sin/assets/135169022/5a0e3943-eab2-4dfe-b99f-dd89b55c005d)

**Comment by dastrukar** [comment]
apparently i made a typo while updating the language stuff
should be back to how it was before now
