### ISSUE TITLE
(Bug) Missing Mutator Settings

### ISSUE THREAD

**Issue by devlman127** [caligari87/Ugly-as-Sin#237]
Most recent version I'm using, 4.11.3.C of both HDest and UaS, I can't find the mutator settings under the addons menu section or anywhere else in the menu. Only two mods active and I'm using the latest GZDoom.

**Comment by caligari87** [comment]
I believe it should be fixed now, redownload. The zip was empty (and I needed to fix a bug with the cvars anyway)

**Comment by devlman127** [comment]
Seems to be fixed. Oddly enough, the new version is half the size as the previous one.
