### ISSUE TITLE
Curse Tweaks ThinkerIterator causing save game issues

### ISSUE THREAD

**Issue by Thecrik** [caligari87/Ugly-as-Sin#241]
Seemingly, any game saves made while 'curse rate' is set to anything other 'Always' will result in a save that cannot be loaded.

<img width="522" alt="consolecapture" src="https://github.com/caligari87/Ugly-as-Sin/assets/48114056/fdf9bc14-4b71-4e5c-968b-6f440c3adb08">

Tested on GZDoom 4.11.3 with HDst 4.11.3d and latest UaS master.

**Comment by caligari87** [comment]
Fixed. Forgot to mark the iterator pointer as transient.
