### ISSUE TITLE
[SUGGESTION]Sniper Elite-style corpse searching

### ISSUE THREAD

**Issue by Silentdarkness12** [caligari87/Ugly-as-Sin#32]
Instead of enemies having the chance to drop their usual loots, you use the use key over a dead body to search it for ammo. A single tap will do a quick search, and giving the e a concentrated series of mashes would do a more thorough, involved search. The quick search would maybe MAYBE drop a little something. The full search would take a fair bit more time, but has a higher chance of giving up something guud.

**Comment by Silentdarkness12** [comment]
Further ideas:

-Zombiemen can very rarely drop a magazine for the weapon they had when they died(and maybe even plug this into scarcity too), rarely drop a stimpack, or usually just a bunch of loose rounds.
-For shotgunners, a 'clip' means the fourpack of shotgun shells, and loose ammo is 1-3 shotgun shells per instance
-For dragon guards, also a small chance to drop a spare battery.
-Marines can possibly drop 7-mil ammo items, and if the player has a reloading kit in their inventory, reloading supplies get automatically added to the kit.

**Comment by Silentdarkness12** [comment]
Drop lists

ZM66 Zombiemen/Jackboots:

_-Stimpack
-Loose 4.26mm rounds(1-10)
-Loose 9mm round(1-5)
-Hand Grenade
Rare Drops:
-Pistol or Automatic Pistol
-9mm Magazine
-4.26 Magazine_

Zombie Shotgunners:

_-Stimpack
-Loose Shotgun Shells(1-5)
-Loose 9mm round(1-5)
-Hand Grenade
Rare Drops:
-Pistol or Automatic Pistol
-9mm Magazine
-Box of Shotgun Shells_

SMG Zombiemen:

_-Stimpack
-Loose 9mm round(1-15)
-9mm Pistol Mag
-Hand Grenade
Rare Drops:
-Pistol or Automatic Pistol
-9mm SMG Magazine
-Box of 9mm ammo_

Dragon Guard:

_-Stimpack
-4.26 Magazine
-Loose 9mm round(1-10)
-9mm Pistol Mag
-Hand Grenade
Rare Drops:
-Pistol or Automatic Pistol
-Additional 4.26 magazine
-Battery_

All Marines and Tango variants therein are guaranteed to drop at least one magazine of the weapon they had on hand, a pistol, a pistol magazine and potentially any of the following:

_-7.76 mm rounds(1-10)
-7.76mm casings(1-20)
-Rocquettes(1-4)
-HEAT Rocket
-Battery
-Dead Battery
-Brontornis Bolt
-Hand Grenades
-Stimpack
-Medikit
-Berserk Pack
-Environment Suit
-Blue Potion(Marine only)
-D.E.R.P/Broken D.E.R.P
-H.E.R.P/Broken H.E.R.P
-IED Kit
-Light Amplification Visor
-Summon Token
-Sniper Rifle Clips
-Liberator Mags
-Armor
-Spiritual Armor_

**Comment by caligari87** [comment]
Added [looting branch](https://github.com/caligari87/Ugly-as-Sin/tree/looting) for testing. Should be mostly stable and feature-complete.

**Comment by caligari87** [comment]
Consider adding some of the flavor-text "nothing found" messages from [NOLF](https://github.com/wilkie/no-one-lives-forever-2/blob/master/Game/ClientRes/TO2/Lang/EN/ClientRes.rc#L3848). These could pop up randomly for each "pocket" check.

**Comment by caligari87** [comment]
Add rations to looting, if Hunger module enabled. Add some more of the above from Sirus/SD's list as well.

**Comment by caligari87** [comment]
List of flavortext suggestions from the HD discord:
https://docs.google.com/document/d/1BX2zhsMEvsJAaakp3us6CoJK2qkbACdw1buSxem1cTg/edit?usp=sharing

**Comment by caligari87** [comment]
Alright, so this is now gameplay-complete and merged to master. Flavortext is next on the "menu".

**Comment by caligari87** [comment]
Some preliminary flavortext added, nothing too complex. Can be easily expanded in the future.
