### ISSUE TITLE
VWep skins

### ISSUE THREAD

**Issue by JRHard771** [caligari87/Ugly-as-Sin#33]
I can't vouch for the utility of these skins, but they exist.

[MarineSkinsV7.zip](https://github.com/caligari87/Ugly-as-Sin/files/2386156/MarineSkinsV7.zip)

**Comment by caligari87** [comment]
Initial working version for `HDMarine` actors  *only* has been pushed to a new [`visweps`](https://github.com/caligari87/Ugly-as-Sin/tree/visweps) branch. Players will be next on the docket, if possible.

Note this only applies to the marine's "canonical" weapon (Hunter, SMG, or RL). It doesn't take pistols into account, at least not yet.

**Comment by caligari87** [comment]
Also the new sprites are in the classic "hipfire" Doom style, which some may find distracting. Spritework is outside the scope of this feature (and my personal skillset) at the moment unless someone else feels inclined to help.

**Comment by caligari87** [comment]
Marines now visually switch to their pistols! This is very nifty.

**Comment by caligari87** [comment]
Added this feature, applies to HDMarine-derived classes only (not players).
