### ISSUE TITLE
Reloader doesn't spawn for custom loadout.

### ISSUE THREAD

**Issue by Fallingferret** [caligari87/Ugly-as-Sin#37]
*Title*
Works fine with classic rifleman and marksman, but doesn't seem to recognize a custom loadout with either the Liberator, or the Boss Rifle.

**Comment by caligari87** [comment]
Probably because custom loadout gets put on player after spawn, not during. Will see about moving my checks forward a tic or two.

**Comment by caligari87** [comment]
Fixed, with a more robust and interesting solution than I had originally anticipated.
