### ISSUE TITLE
5-6 people crashes multi

### ISSUE THREAD

**Issue by caligari87** [caligari87/Ugly-as-Sin#74]
Reported in Discord. Starting a multiplayer game on Doom 2 MAP01 with 5+ people results in a silent crash if UaS is loaded.

**Comment by nicothegoat** [comment]
For some reason, players 5-8 don't have a PlayerPawn in the PlayerEntered event.
Fixed (partially) in #104

**Comment by caligari87** [comment]
Have decided to wait on engine support for this one.

**Comment by caligari87** [comment]
Worked around many possible crashes by moving player initialization to a WorldTick handler instead of using PlayerEntered. Will require testing but hopefully this should fix the worst issues.

**Comment by caligari87** [comment]
Closing per the above fix. Not enough testing but no reason why it should cause problems.
