### ISSUE TITLE
Stealth module suggestion: Shotgunners only use flashlights

### ISSUE THREAD

**Issue by BiggestC** [caligari87/Ugly-as-Sin#87]
Already told you about this idea, just sticky-noting it for posterity. :P

**Comment by caligari87** [comment]
Easy enough to do, but will handle as part of the larger refactor project. Most gun monsters will use unified light/laser module in dual mode if dark enough.

**Comment by caligari87** [comment]
Closing after laser/light refactor. Monsters with this item will turn on flashlights in the dark regardless.
