### ISSUE TITLE
Cannot open with hideous destructor

### ISSUE THREAD

**Issue by Vantablack1834** [caligari87/Ugly-as-Sin#91]
Script error, ":modules/ai/flashlight.zsc" line 15:
Unknown class name 'RedPillbox' of type 'Actor'
Script error, ":modules/ai/flashlight.zsc" line 18:
Unknown identifier 'validClass'
Script error, ":modules/looting/looting.zsc" line 134:
Unknown class name 'RedPillbox' of type 'Actor'
Script warning, ":modules/lights/items.zsc" line 51:
Truncation of floating point constant 0.150000

Execution could not continue.

3 errors while parsing DECORATE scripts

I have gotten this whenever i try to launch it.

**Comment by caligari87** [comment]
You are on an old version of Hideous Destructor. Latest releases have renamed the Chaingunner class and Ugly as Sin has been updated to match.
