### ISSUE TITLE
Address zero crash from looting

### ISSUE THREAD

**Issue by caligari87** [caligari87/Ugly-as-Sin#92]
Reported on Discord by Sirus#6414 and BuilderMantis#8336. Crash during a multiplayer game while looting a "dead rifleman". 

![Screenshot](https://cdn.discordapp.com/attachments/462331550768431104/560865099598790657/unknown.png)

Loaded with [Sirus's "Mystery Box" addon](https://cdn.discordapp.com/attachments/462331550768431104/560867161573425152/UaS_LootMutator_MarineMysteryBox.wad) to expand loot lists. 

Error appears to be in the call to `Spawn`, possibly passing a null type name.

**Comment by scrumbo** [comment]
![image](https://user-images.githubusercontent.com/55452593/65868484-3d8cf100-e370-11e9-9225-d5d03c3dec9f.png)

For what it's worth, I had a similar crash while looting a marine's corpse, but _not_ using Sirus's or any other addon, it's just HD and Ugly-as-Sin

**Comment by caligari87** [comment]
Fixed (presumably) in #101. Will reopen if this appears to be a different issue.
